# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.AccountBalance do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :balance,
    :threshold,
    :currency,
    :active
  ]

  @type t :: %__MODULE__{
          :balance => float(),
          :threshold => float(),
          :currency => String.t(),
          :active => boolean()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.AccountBalance do
  def decode(value, _options) do
    value
  end
end
