# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.AccountBalanceResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :accountBalance
  ]

  @type t :: %__MODULE__{
          :accountBalance => AccountBalance
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.AccountBalanceResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:accountBalance, :struct, Voxbone.Model.AccountBalance, options)
  end
end
