# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.AddToCartRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cartIdentifier,
    :didCartItem,
    :capacityCartItem,
    :creditPackageCartItem
  ]

  @type t :: %__MODULE__{
          :cartIdentifier => integer(),
          :didCartItem => DidCartItem,
          :capacityCartItem => CapacityCartItem,
          :creditPackageCartItem => CreditPackageCartItem
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.AddToCartRequest do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:didCartItem, :struct, Voxbone.Model.DidCartItem, options)
    |> deserialize(:capacityCartItem, :struct, Voxbone.Model.CapacityCartItem, options)
    |> deserialize(:creditPackageCartItem, :struct, Voxbone.Model.CreditPackageCartItem, options)
  end
end
