# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CapacityGroupModel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :capacityGroupId,
    :maximumCapacity,
    :description,
    :amountOfDidsMapped
  ]

  @type t :: %__MODULE__{
          :capacityGroupId => integer(),
          :maximumCapacity => integer(),
          :description => String.t(),
          :amountOfDidsMapped => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CapacityGroupModel do
  def decode(value, _options) do
    value
  end
end
