# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Cart do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cartIdentifier,
    :customerReference,
    :description,
    :dateAdded,
    :orderProducts
  ]

  @type t :: %__MODULE__{
          :cartIdentifier => integer(),
          :customerReference => String.t(),
          :description => String.t(),
          :dateAdded => String.t(),
          :orderProducts => [OrderProduct]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Cart do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:orderProducts, :list, Voxbone.Model.OrderProduct, options)
  end
end
