# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CityZipCode do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cityName,
    :zipCode
  ]

  @type t :: %__MODULE__{
          :cityName => String.t(),
          :zipCode => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CityZipCode do
  def decode(value, _options) do
    value
  end
end
