# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ContentDisposition do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :filename,
    :parameters
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :filename => String.t(),
          :parameters => %{optional(String.t()) => String.t()}
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ContentDisposition do
  def decode(value, _options) do
    value
  end
end
