# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CreateCartResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cart
  ]

  @type t :: %__MODULE__{
          :cart => Cart
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CreateCartResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:cart, :struct, Voxbone.Model.Cart, options)
  end
end
