# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CreateProofOfIdRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :addressId,
    :nationality,
    :identityDocumentType,
    :identityDocumentNumber,
    :issuingAuthority,
    :issuingDate
  ]

  @type t :: %__MODULE__{
          :addressId => integer(),
          :nationality => String.t(),
          :identityDocumentType => String.t(),
          :identityDocumentNumber => String.t(),
          :issuingAuthority => String.t(),
          :issuingDate => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CreateProofOfIdRequest do
  def decode(value, _options) do
    value
  end
end
