# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CreateRegulationAddressRequest do
  @moduledoc """
  Model for Create Regulation Address request
  """

  @derive [Poison.Encoder]
  defstruct [
    :salutation,
    :companyName,
    :companyDescription,
    :firstName,
    :lastName,
    :countryCodeA3,
    :city,
    :zipCode,
    :streetName,
    :buildingNumber,
    :buildingLetter,
    :customerReference,
    :phoneNumber,
    :extraFields,
    :didType,
    :destinationCountryCodeA3,
    :identityDocumentProof
  ]

  @type t :: %__MODULE__{
          :salutation => String.t(),
          :companyName => String.t(),
          :companyDescription => String.t(),
          :firstName => String.t(),
          :lastName => String.t(),
          :countryCodeA3 => String.t(),
          :city => String.t(),
          :zipCode => String.t(),
          :streetName => String.t(),
          :buildingNumber => String.t(),
          :buildingLetter => String.t(),
          :customerReference => String.t(),
          :phoneNumber => String.t(),
          :extraFields => ExtraFields,
          :didType => String.t(),
          :destinationCountryCodeA3 => String.t(),
          :identityDocumentProof => IdentityDocumentProof
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CreateRegulationAddressRequest do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:extraFields, :struct, Voxbone.Model.ExtraFields, options)
    |> deserialize(:identityDocumentProof, :struct, Voxbone.Model.IdentityDocumentProof, options)
  end
end
