# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CreditPackage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :creditPackageId,
    :name,
    :price100
  ]

  @type t :: %__MODULE__{
          :creditPackageId => integer(),
          :name => String.t(),
          :price100 => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CreditPackage do
  def decode(value, _options) do
    value
  end
end
