# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.CreditPackageCartItem do
  @moduledoc """
  CreditPackageCartItem corresponds to prepaid credits.
  """

  @derive [Poison.Encoder]
  defstruct [
    :creditPackageId,
    :quantity
  ]

  @type t :: %__MODULE__{
          :creditPackageId => integer(),
          :quantity => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.CreditPackageCartItem do
  def decode(value, _options) do
    value
  end
end
