# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.DataHandler do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :dataSource,
    :transferDataFlavors,
    :preferredCommands,
    :contentType,
    :outputStream,
    :allCommands,
    :name,
    :inputStream,
    :content
  ]

  @type t :: %__MODULE__{
          :dataSource => DataSource,
          :transferDataFlavors => [DataFlavor],
          :preferredCommands => [CommandInfo],
          :contentType => String.t(),
          :outputStream => OutputStream,
          :allCommands => [CommandInfo],
          :name => String.t(),
          :inputStream => InputStream,
          :content => Object
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.DataHandler do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:dataSource, :struct, Voxbone.Model.DataSource, options)
    |> deserialize(:transferDataFlavors, :list, Voxbone.Model.DataFlavor, options)
    |> deserialize(:preferredCommands, :list, Voxbone.Model.CommandInfo, options)
    |> deserialize(:outputStream, :struct, Voxbone.Model.OutputStream, options)
    |> deserialize(:allCommands, :list, Voxbone.Model.CommandInfo, options)
    |> deserialize(:inputStream, :struct, Voxbone.Model.InputStream, options)
    |> deserialize(:content, :struct, Voxbone.Model.Object, options)
  end
end
