# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.DidCartItem do
  @moduledoc """
  DidCartItem corresponds to DIDs (VoxDID or Vox800).
  """

  @derive [Poison.Encoder]
  defstruct [
    :didGroupId,
    :quantity
  ]

  @type t :: %__MODULE__{
          :didGroupId => integer(),
          :quantity => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.DidCartItem do
  def decode(value, _options) do
    value
  end
end
