# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.DidConfigurationResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :messages
  ]

  @type t :: %__MODULE__{
          :messages => [ConfigurationOptionStatus]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.DidConfigurationResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:messages, :list, Voxbone.Model.ConfigurationOptionStatus, options)
  end
end
