# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ExtraFields do
  @moduledoc """
  These are extra address parameters that are required in certain countries and for certain DID types.
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :province,
    :firstName,
    :lastName,
    :streetCode,
    :municipalityCode,
    :nationality,
    :idType,
    :dateOfBirth,
    :placeOfBirth,
    :companyVatNumber,
    :taxCode,
    :idNumber,
    :fiscalIdentificationCode,
    :state
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :province => String.t(),
          :firstName => String.t(),
          :lastName => String.t(),
          :streetCode => String.t(),
          :municipalityCode => String.t(),
          :nationality => String.t(),
          :idType => String.t(),
          :dateOfBirth => String.t(),
          :placeOfBirth => String.t(),
          :companyVatNumber => String.t(),
          :taxCode => String.t(),
          :idNumber => String.t(),
          :fiscalIdentificationCode => String.t(),
          :state => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ExtraFields do
  def decode(value, _options) do
    value
  end
end
