# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Feature do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :featureId,
    :name,
    :description
  ]

  @type t :: %__MODULE__{
          :featureId => integer(),
          :name => String.t(),
          :description => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Feature do
  def decode(value, _options) do
    value
  end
end
