# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.IsAddressValidResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :isValid,
    :reasons
  ]

  @type t :: %__MODULE__{
          :isValid => boolean(),
          :reasons => [Reason]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.IsAddressValidResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:reasons, :list, Voxbone.Model.Reason, options)
  end
end
