# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.LinkRegulationAddressResponse do
  @moduledoc """
  This is the result of the operation if successful. If you have successfully linked/unlinked the DIDs then you get the status NUMBERS_LINKED_AND_UNBLOCKED, NUMBERS_LINKED_PENDING_ADDRESS_VALIDATION or NUMBERS_UNLINKED_AND_BLOCKED.
  """

  @derive [Poison.Encoder]
  defstruct [
    :status
  ]

  @type t :: %__MODULE__{
          :status => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.LinkRegulationAddressResponse do
  def decode(value, _options) do
    value
  end
end
