# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListExistingFilesResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :fileNames
  ]

  @type t :: %__MODULE__{
          :fileNames => [String.t()]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListExistingFilesResponse do
  def decode(value, _options) do
    value
  end
end
