# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListFaxUriResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :faxUris,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :faxUris => [FaxUri],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListFaxUriResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:faxUris, :list, Voxbone.Model.FaxUri, options)
  end
end
