# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListDidResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :dids,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :dids => [Did],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListDidResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:dids, :list, Voxbone.Model.Did, options)
  end
end
