# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListRegulationAddressResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :regulationAddresses,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :regulationAddresses => [RegulationAddress],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListRegulationAddressResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:regulationAddresses, :list, Voxbone.Model.RegulationAddress, options)
  end
end
