# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListSmsLinkGroupResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :smsLinkGroups
  ]

  @type t :: %__MODULE__{
          :smsLinkGroups => [SmsLinkGroup]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListSmsLinkGroupResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:smsLinkGroups, :list, Voxbone.Model.SmsLinkGroup, options)
  end
end
