# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListCreditPackageResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :creditPackages
  ]

  @type t :: %__MODULE__{
          :creditPackages => [CreditPackage]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListCreditPackageResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:creditPackages, :list, Voxbone.Model.CreditPackage, options)
  end
end
