# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListDidGroupResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :didGroups,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :didGroups => [DidGroup],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListDidGroupResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:didGroups, :list, Voxbone.Model.DidGroup, options)
  end
end
