# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListCountryResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :countries,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :countries => [Country],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListCountryResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:countries, :list, Voxbone.Model.Country, options)
  end
end
