# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListCapacityGroupResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :capacityGroups,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :capacityGroups => [CapacityGroupModel],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListCapacityGroupResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:capacityGroups, :list, Voxbone.Model.CapacityGroupModel, options)
  end
end
