# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListTrunkResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :trunks
  ]

  @type t :: %__MODULE__{
          :trunks => [Trunk]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListTrunkResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:trunks, :list, Voxbone.Model.Trunk, options)
  end
end
