# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListRestrictionResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :restrictions
  ]

  @type t :: %__MODULE__{
          :restrictions => [Restriction]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListRestrictionResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:restrictions, :list, Voxbone.Model.Restriction, options)
  end
end
