# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListStateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :states
  ]

  @type t :: %__MODULE__{
          :states => [State]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListStateResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:states, :list, Voxbone.Model.State, options)
  end
end
