# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListCartResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :carts,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :carts => [Cart],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListCartResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:carts, :list, Voxbone.Model.Cart, options)
  end
end
