# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListOrderResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :orders,
    :resultCount
  ]

  @type t :: %__MODULE__{
          :orders => [Order],
          :resultCount => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListOrderResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:orders, :list, Voxbone.Model.Order, options)
  end
end
