# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListFeatureResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :features
  ]

  @type t :: %__MODULE__{
          :features => [Feature]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListFeatureResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:features, :list, Voxbone.Model.Feature, options)
  end
end
