# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListVoiceUri do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :voiceUriId,
    :backupUriId,
    :backupUri,
    :voiceUriProtocol,
    :uri,
    :description
  ]

  @type t :: %__MODULE__{
          :voiceUriId => integer(),
          :backupUriId => integer(),
          :backupUri => String.t(),
          :voiceUriProtocol => String.t(),
          :uri => String.t(),
          :description => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListVoiceUri do
  def decode(value, _options) do
    value
  end
end
