# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ListSmsLinkResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :smsLinks
  ]

  @type t :: %__MODULE__{
          :smsLinks => [SmsLinkModel]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ListSmsLinkResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:smsLinks, :list, Voxbone.Model.SmsLinkModel, options)
  end
end
