# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.MediaType do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :subtype,
    :parameters,
    :wildcardType,
    :wildcardSubtype
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :subtype => String.t(),
          :parameters => %{optional(String.t()) => String.t()},
          :wildcardType => boolean(),
          :wildcardSubtype => boolean()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.MediaType do
  def decode(value, _options) do
    value
  end
end
