# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Order do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :orderId,
    :reference,
    :dateAdded,
    :dateCanceled,
    :status,
    :customerReference
  ]

  @type t :: %__MODULE__{
          :orderId => integer(),
          :reference => String.t(),
          :dateAdded => String.t(),
          :dateCanceled => String.t(),
          :status => String.t(),
          :customerReference => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Order do
  def decode(value, _options) do
    value
  end
end
