# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Pop do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :deliveryId,
    :name,
    :ips
  ]

  @type t :: %__MODULE__{
          :deliveryId => integer(),
          :name => String.t(),
          :ips => [String.t()]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Pop do
  def decode(value, _options) do
    value
  end
end
