# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.ProductCheckout do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :productType,
    :status,
    :orderReference,
    :message
  ]

  @type t :: %__MODULE__{
          :productType => String.t(),
          :status => String.t(),
          :orderReference => String.t(),
          :message => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.ProductCheckout do
  def decode(value, _options) do
    value
  end
end
