# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Reason do
  @moduledoc """
  If the address is not valid for the requested country and DID type, a reason is returned with a code and message.
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :message
  ]

  @type t :: %__MODULE__{
          :code => String.t(),
          :message => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Reason do
  def decode(value, _options) do
    value
  end
end
