# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.RegulationAddress do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :addressId,
    :linked,
    :status,
    :salutation,
    :companyName,
    :companyDescription,
    :firstName,
    :lastName,
    :countryCodeA3,
    :city,
    :zipCode,
    :streetName,
    :buildingNumber,
    :buildingLetter,
    :customerReference,
    :extraFields,
    :rejectionReasons
  ]

  @type t :: %__MODULE__{
          :addressId => integer(),
          :linked => boolean(),
          :status => String.t(),
          :salutation => String.t(),
          :companyName => String.t(),
          :companyDescription => String.t(),
          :firstName => String.t(),
          :lastName => String.t(),
          :countryCodeA3 => String.t(),
          :city => String.t(),
          :zipCode => String.t(),
          :streetName => String.t(),
          :buildingNumber => String.t(),
          :buildingLetter => String.t(),
          :customerReference => String.t(),
          :extraFields => ExtraFields,
          :rejectionReasons => [String.t()]
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.RegulationAddress do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:extraFields, :struct, Voxbone.Model.ExtraFields, options)
  end
end
