# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.RegulationRequirementModel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :addressType,
    :proofRequired
  ]

  @type t :: %__MODULE__{
          :addressType => String.t(),
          :proofRequired => boolean()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.RegulationRequirementModel do
  def decode(value, _options) do
    value
  end
end
