# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.RemoveFromCartRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cartIdentifier,
    :orderProductId,
    :quantity
  ]

  @type t :: %__MODULE__{
          :cartIdentifier => integer(),
          :orderProductId => integer(),
          :quantity => integer()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.RemoveFromCartRequest do
  def decode(value, _options) do
    value
  end
end
