# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.RequestFileCreationRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :month,
    :year,
    :type
  ]

  @type t :: %__MODULE__{
          :month => String.t(),
          :year => String.t(),
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.RequestFileCreationRequest do
  def decode(value, _options) do
    value
  end
end
