# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.Restriction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :countryCodeA3,
    :restrictionType,
    :restrictionMessage
  ]

  @type t :: %__MODULE__{
          :countryCodeA3 => String.t(),
          :restrictionType => String.t(),
          :restrictionMessage => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.Restriction do
  def decode(value, _options) do
    value
  end
end
