# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SaveFaxUriRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :faxUri
  ]

  @type t :: %__MODULE__{
          :faxUri => SaveFaxUri
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SaveFaxUriRequest do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:faxUri, :struct, Voxbone.Model.SaveFaxUri, options)
  end
end
