# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SaveFaxUri do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :faxUriId,
    :deliveryMethod,
    :faxFileFormat,
    :uri,
    :csid,
    :subject,
    :body,
    :useHtml
  ]

  @type t :: %__MODULE__{
          :faxUriId => integer(),
          :deliveryMethod => String.t(),
          :faxFileFormat => String.t(),
          :uri => String.t(),
          :csid => String.t(),
          :subject => String.t(),
          :body => String.t(),
          :useHtml => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SaveFaxUri do
  def decode(value, _options) do
    value
  end
end
