# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SaveSmsLinkRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :smsLink
  ]

  @type t :: %__MODULE__{
          :smsLink => SmsLinkModel
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SaveSmsLinkRequest do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:smsLink, :struct, Voxbone.Model.SmsLinkModel, options)
  end
end
