# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SaveVoiceUriResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :voiceUri
  ]

  @type t :: %__MODULE__{
          :voiceUri => SaveVoiceUri
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SaveVoiceUriResponse do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:voiceUri, :struct, Voxbone.Model.SaveVoiceUri, options)
  end
end
