# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SingleDidConfigurationRequest do
  @moduledoc """
  Model for Apply DID Configuration request
  """

  @derive [Poison.Encoder]
  defstruct [
    :didId,
    :voiceUriId,
    :smsLinkGroupId,
    :faxUriId,
    :voxFaxEnabled,
    :capacityGroupId,
    :trunkId,
    :deliveryId,
    :srvLookup,
    :callerId,
    :cliPrivacy,
    :peer,
    :ringback,
    :dnisEnabled,
    :blockOrdinary,
    :blockCellular,
    :blockPayphone,
    :smsOutbound,
    :webRtcEnabled,
    :limitChannels,
    :voxoutInternationalEnabled,
    :voxoutNationalEnabled
  ]

  @type t :: %__MODULE__{
          :didId => integer(),
          :voiceUriId => integer(),
          :smsLinkGroupId => integer(),
          :faxUriId => integer(),
          :voxFaxEnabled => boolean(),
          :capacityGroupId => integer(),
          :trunkId => integer(),
          :deliveryId => integer(),
          :srvLookup => boolean(),
          :callerId => CallerId,
          :cliPrivacy => String.t(),
          :peer => Peer,
          :ringback => String.t(),
          :dnisEnabled => boolean(),
          :blockOrdinary => boolean(),
          :blockCellular => boolean(),
          :blockPayphone => boolean(),
          :smsOutbound => boolean(),
          :webRtcEnabled => boolean(),
          :limitChannels => String.t(),
          :voxoutInternationalEnabled => boolean(),
          :voxoutNationalEnabled => boolean()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SingleDidConfigurationRequest do
  import Voxbone.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:callerId, :struct, Voxbone.Model.CallerId, options)
    |> deserialize(:peer, :struct, Voxbone.Model.Peer, options)
  end
end
