# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.SmsLinkModel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :smsLinkId,
    :login,
    :password,
    :url,
    :groupId,
    :type,
    :name,
    :direction,
    :weight,
    :systemType,
    :useSSL,
    :monitorInterval,
    :transactionTimeout,
    :deliveryStatusReport
  ]

  @type t :: %__MODULE__{
          :smsLinkId => integer(),
          :login => String.t(),
          :password => String.t(),
          :url => String.t(),
          :groupId => integer(),
          :type => String.t(),
          :name => String.t(),
          :direction => String.t(),
          :weight => integer(),
          :systemType => String.t(),
          :useSSL => boolean(),
          :monitorInterval => integer(),
          :transactionTimeout => integer(),
          :deliveryStatusReport => boolean()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.SmsLinkModel do
  def decode(value, _options) do
    value
  end
end
