# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Model.State do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :stateId,
    :stateName,
    :stateCode,
    :countryCodeA3
  ]

  @type t :: %__MODULE__{
          :stateId => integer(),
          :stateName => String.t(),
          :stateCode => String.t(),
          :countryCodeA3 => String.t()
        }
end

defimpl Poison.Decoder, for: Voxbone.Model.State do
  def decode(value, _options) do
    value
  end
end
