# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Connection do
  @moduledoc """
  Handle Tesla connections for Voxbone.
  """

  @base_url %{
    sandbox: "https://sandbox.voxbone.com/ws-voxbone/services/rest/"
  }

  use Tesla

  adapter(:hackney)

  # Add any middleware here (authentication)
  plug(Tesla.Middleware.Headers, %{
    "User-Agent" => "Elixir",
    "Accept" => "application/json"
  })

  plug(Tesla.Middleware.EncodeJson)

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client()
  def new do
    base_url = Map.fetch!(@base_url, Application.get_env(:voxbone, :environment, :sandbox))

    Tesla.build_client([
      {Tesla.Middleware.BaseUrl, base_url},
      {Tesla.Middleware.BasicAuth,
       %{
         username: Application.fetch_env!(:voxbone, :username),
         password: Application.fetch_env!(:voxbone, :password)
       }}
    ])
  end
end
