# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Voxbone.Connection do
  @moduledoc """
  Handle Tesla connections for Voxbone.
  """

  @base_url %{
    sandbox: "https://sandbox.voxbone.com/ws-voxbone/services/rest/",
    production: "https://api.voxbone.com/ws-voxbone/services/rest"
  }

  use Tesla

  adapter(:ibrowse)

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client()
  def new do
    base_url = Map.fetch!(@base_url, Application.get_env(:voxbone, :environment, :sandbox))

    middleware = [
      {Tesla.Middleware.BaseUrl, base_url},
      {Tesla.Middleware.BasicAuth,
       %{
         username: Application.fetch_env!(:voxbone, :username),
         password: Application.fetch_env!(:voxbone, :password)
       }},
      Tesla.Middleware.EncodeJson,
      {Tesla.Middleware.Headers,
       %{
         "User-Agent" => "Elixir",
         "Accept" => "application/json"
       }}
    ]

    middleware =
      if Application.get_env(:voxbone, :debug, false) do
        middleware ++ [Tesla.Middleware.DebugLogger]
      else
        middleware
      end

    Tesla.build_client(middleware)
  end
end
